# -*- coding: utf-8 -*-
"""notebook_05.ipynb의 사본

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f1UziYJZSIwbbJidYf2R-bVazabOE7ae

# Notebook 5 — Single-Head Masked Self-Attention

이제 GPT의 핵심 아이디어인 **masked self-attention**을 추가합니다.

이번 단계에서는 **single-head**에만 집중합니다.
"""

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader
from pathlib import Path

if not Path("input.txt").exists():
    !wget -q https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt

text = open("input.txt", "r", encoding="utf-8").read()
chars = sorted(list(set(text)))
stoi = {ch: i for i, ch in enumerate(chars)}
itos = {i: ch for ch, i in stoi.items()}
vocab_size = len(chars)
data = torch.tensor([stoi[ch] for ch in text], dtype=torch.long)

class NextTokenDataset(Dataset):
    def __init__(self, data, block_size):
        self.data = data
        self.block_size = block_size
    def __len__(self):
        return len(self.data) - self.block_size
    def __getitem__(self, idx):
        x = self.data[idx : idx + self.block_size]
        y = self.data[idx + 1 : idx + self.block_size + 1]
        return x, y

block_size = 32
dataset = NextTokenDataset(data, block_size)
loader = DataLoader(dataset, batch_size=64, shuffle=True)
xb, yb = next(iter(loader))

"""## 1. Single-head masked self-attention"""

class SingleHeadSelfAttention(nn.Module):
    def __init__(self, emb_dim, block_size):
        super().__init__()
        self.key = nn.Linear(emb_dim, emb_dim, bias=False)
        self.query = nn.Linear(emb_dim, emb_dim, bias=False)
        self.value = nn.Linear(emb_dim, emb_dim, bias=False)
        self.register_buffer("tril", torch.tril(torch.ones(block_size, block_size)))

    def forward(self, x):
        B, T, C = x.shape
        k = self.key(x) # 각각을 linear로 만들어줌
        q = self.query(x)
        v = self.value(x)


        # 밑에 세 줄이 핵심 attention
        wei = q @ k.transpose(-2, -1) * (C ** -0.5)
        # wei[b,t,s] = b번째 batch에서 t번째 위치가 s번째 위치를 얼마나 참고할지에 대한 점수
        # (c**-0.5)는 scaling. dimension은 변하지 않음
        wei = wei.masked_fill(self.tril[:T, :T] == 0, float("-inf")) # 미래를 보지 못하게 하는 mask
        wei = F.softmax(wei, dim=-1) # 맨 뒤에 것을 기준으로 확률 설정


        out = wei @ v
        # out[b,t,:] : t번째 위치가 참고 가능한 과거 위치들의 value vector를 가중평균한 결과

        return out

"""## 2. Attention 포함 최소 모델"""

class TinyAttentionLM(nn.Module):
    def __init__(self, vocab_size, block_size, emb_dim=64):
        super().__init__()
        self.token_embedding = nn.Embedding(vocab_size, emb_dim)
        self.position_embedding = nn.Embedding(block_size, emb_dim)
        self.attn = SingleHeadSelfAttention(emb_dim, block_size)
        self.lm_head = nn.Linear(emb_dim, vocab_size)

    def forward(self, x):
        B, T = x.shape
        pos = torch.arange(T, device=x.device) # 위치 번호
        tok = self.token_embedding(x)
        pos = self.position_embedding(pos)[None] # [None] : 맨 앞 dimension을 하나 추가 [64,32] -> [1,64,32]. unsquezee랑 비슷
        h = tok + pos # 원래는 broadcasting에 의해 자동으로 더해지지만, 위에서 명시적으로 dimension을 맞춰줌
        h = self.attn(h)
        logits = self.lm_head(h)
        return logits

model = TinyAttentionLM(vocab_size, block_size)
logits = model(xb)
print("logits.shape:", logits.shape)

"""## 3. 학습"""

def sequence_cross_entropy(logits, targets):
    return F.cross_entropy(logits.transpose(1, 2), targets)

def train_one_epoch(model, loader, optimizer, device, max_steps=None):
    model.train()
    total_loss, total_count = 0.0, 0
    for step, (xb, yb) in enumerate(loader):
        xb, yb = xb.to(device), yb.to(device)
        logits = model(xb)
        loss = sequence_cross_entropy(logits, yb)
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        total_loss += loss.item() * xb.size(0)
        total_count += xb.size(0)
        if max_steps is not None and step + 1 >= max_steps:
            break
    return total_loss / total_count

device = "cuda" if torch.cuda.is_available() else "cpu"
model = TinyAttentionLM(vocab_size, block_size).to(device)
optimizer = torch.optim.AdamW(model.parameters(), lr=1e-3)

for epoch in range(100):
    train_loss = train_one_epoch(model, loader, optimizer, device, max_steps=300)
    print(f"epoch {epoch:2d} | train loss {train_loss:.4f}")

"""## 4. Sampling"""

@torch.no_grad()
def sample_attention_model(model, block_size, stoi, itos, device, start_text="ROMEO:", max_new_tokens=300):
    model.eval()
    context = torch.zeros((1, block_size), dtype=torch.long, device=device)
    for ch in start_text:
        if ch in stoi:
            ix = torch.tensor([[stoi[ch]]], device=device)
            context = torch.cat([context[:, 1:], ix], dim=1)
    out = list(start_text)
    for _ in range(max_new_tokens):
        logits = model(context)
        logits = logits[:, -1, :]
        probs = F.softmax(logits, dim=-1)
        ix = torch.multinomial(probs, num_samples=1)
        out.append(itos[ix.item()])
        context = torch.cat([context[:, 1:], ix], dim=1)
    return "".join(out)

print(sample_attention_model(model, block_size, stoi, itos, device, start_text="ROMEO:", max_new_tokens=400))

"""## 5. 정리

- 각 위치는 이전 위치들을 참조할 수 있습니다.
- 미래는 causal mask로 차단됩니다.
- 이제 모델이 어떤 위치를 참고할지 스스로 결정하기 시작합니다.
"""